#!/bin/bash

export BOOST_ROOT=$1
export TARGET_OS=$2

export PREV_DIR=$(pwd)

cd $BOOST_ROOT

# booststrap boost
./bootstrap.sh

# setup b2 user config base on target os argument
if [[ "$TARGET_OS" = "windows" ]]; then
	# cross compiling windows, setup mingw toolset
	echo "-- Setting up cross compiler"
	echo "using gcc : mingw : i686-w64-mingw32-g++;" > user-config.jam
	export B2_ARGS="toolset=gcc-mingw target-os=windows"
else
	export B2_ARGS="target-os=linux"
fi

# run boost build
echo "-- Running Boost.Build Engine"
./b2 $B2_ARGS --with-system --with-thread

# go back
cd $PREV_DIR

