#!/bin/bash

# boost variables
export BOOST_VERSION=$1
export BOOST_NAME="boost_$(echo "$BOOST_VERSION" | tr . _)"
export BOOST_TAR_FILE="$BOOST_NAME.tar.gz"
export DOWNLOAD_URL="http://downloads.sourceforge.net/project/boost/boost/$BOOST_VERSION/$BOOST_TAR_FILE"

# download boost
echo "-- Downloading Boost $BOOST_VERSION"
wget $DOWNLOAD_URL -P ~/tmp

# extract to /opt
echo "-- Extracting boost to /opt/$BOOST_NAME"
tar -xf ~/tmp/$BOOST_TAR_FILE -C ~/tmp/
sudo mv ~/tmp/$BOOST_NAME /opt
ls /opt

# booststrap boost
#build_boost /opt/$BOOST_NAME $2

# create a setup shell script that contains the BOOST_ROOT env variable
sudo echo "export BOOST_ROOT=/opt/$BOOST_NAME" > /opt/BOOST_NAME/setup.bash

# clean up
unset BOOST_VERSION
unset BOOST_NAME
unset BOOST_TAR_FILE
unset DOWNLOAD_URL
