#!/bin/bash

if [ "$CXX" == "g++" ]; then sudo apt-get install g++-4.8 -qq; fi

# install test frameworks
# install cxxtest
sudo apt-get install cxxtest -qq

# install gtest
git clone https://github.com/google/googletest.git ~/gtest
mkdir ~/gtest/build && cd ~/gtest/build
cmake ..
make && sudo make install
cd -

# install cppcheck
pushd
git clone https://github.com/danmar/cppcheck ~/cppcheck
cd ~/cppcheck
make CXXFLAGS="-O2 -DNDEBUG" && sudo make install
popd
