#!/bin/bash

if [ "$CXX" == "g++" ]; then sudo apt-get install g++-4.8 -qq; fi

# install test frameworks
# install cxxtest
sudo apt-get install cxxtest -qq

# install gtest
git clone https://github.com/google/googletest.git ~/gtest
mkdir ~/gtest/build && cd ~/gtest/build
cmake ..
make && sudo make install
cd -

# install cppcheck
pushd $(pwd)
#sudo apt install libpcre3-dev
#git clone https://github.com/danmar/cppcheck ~/cppcheck
#cd ~/cppcheck
#make SRCDIR=build CFGDIR=/usr/share/cppcheck HAVE_RULES=yes CXXFLAGS="-O2 -DNDEBUG"
#sudo make install CFGDIR=/usr/share/cppcheck
popd
