#!/usr/bin/env python

import sys
import os

boost_components = []

for component in sys.argv[1:]:
	boost_components.append("libboost-%s-dev" % (component))

dep_list = "".join((c + " ") for c in boost_components)

print "installing the following boost components:"
print "".join(("-- %s\n" % s) for s in dep_list.rstrip().split(' '))

cmd = "sudo apt-get install -qq %s" % (dep_list)

os.system(cmd)
