#!/bin/bash

if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

sudo echo "\ndeb http://ppa.launchpad.net/kedazo/doxygen-updates-precise/ubuntu precise main" >> /etc/apt/sources.list
sudo echo "\ndeb-src http://ppa.launchpad.net/kedazo/doxygen-updates-precise/ubuntu precise main" >> /etc/apt/sources.list

sudo apt-get update -qq
